#!/usr/bin/env bun
// Build the plugin-distribution assets from the same skill/ sources the installers use.
//
// The clone install substitutes an ABSOLUTE clone path into the /wiki-* files (claude-commands.ts)
// because the clone can live anywhere. A plugin cannot know its path at build time — Claude Code
// copies it into a versioned cache directory — so the plugin surfaces substitute the runtime
// variable instead:
//
//   skills/wiki-*/SKILL.md    ONE surface for BOTH harnesses. Claude Code exposes a skill as its
//                             /name slash command, and both harnesses inject "Base directory for
//                             this skill" into the body — so a single prose rule ("plugin root is
//                             two levels up") resolves the engine everywhere. A parallel
//                             commands/ dir was measured to DOUBLE the inventory (each command is
//                             also counted as a skill: 10 entries, 2× always-on tokens), so no
//                             commands/ is emitted. Native skills are also REQUIRED for Codex:
//                             its command→skill migration caps a command at 4,000 bytes.
//
// Deterministic and idempotent: run it after editing skill/*.md, commit the outputs. The test in
// tests/plugin-assets.test.ts fails when the committed outputs drift from the sources.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CLONE_ROOT, ENGINE_CLI_TOKEN } from "../engine/paths.ts";
import { CLAUDE_COMMANDS } from "../engine/claude-commands.ts";
import { FRONTMATTER_GATE, SKILL_POLICY_REL, skillPolicyYaml } from "../engine/skill-policy.ts";

export const PLUGIN_MARK = "<!-- generated by src/plugin/build-assets.ts — edit skill/*.md, then re-run -->";

// Neither surface needs a build-time path: both harnesses tell the model the skill's own base
// directory, and the engine sits exactly two levels above skills/<name>/SKILL.md.
//
// That relative rule holds for every host that installs the plugin WHOLE (Claude Code, Codex —
// both copy the tracked tree into a cache). It does NOT hold for a host that copies skill folders
// OUT of it: OpenClaw's `openclaw skills install` lands them in a workspace `skills/` directory,
// Hermes and `npx skills add` land them under `~/.hermes/skills` / `~/.claude/skills`. Two levels
// up is then the host's own skills root — no engine there. So the rule is an ordered resolution
// whose FIRST step is the unchanged plugin/clone case, and whose later steps only ever run where
// the first one already failed. `LLMWIKI_ROOT` is the same variable the OpenCode and OpenClaw
// adapters read; `llmwiki` on PATH is the launcher setup.sh writes to ~/.local/bin (and the npm
// `bin` entry). Guessing is explicitly forbidden: a wrong root writes wiki pages into the wrong
// repository, which is worse than saying "not installed" and stopping.
const CODEX_CLI_NOTE =
  "> Engine invocation — resolve it ONCE, in this order, and use the first that exists:\n" +
  '> 1. `bun "<plugin-root>/src/cli.ts"`, where `<plugin-root>` is the directory TWO levels above\n' +
  ">    this skill's base directory (skills/<name>/ → plugin root). This is the plugin and clone\n" +
  ">    install — the normal case. Stop here when that file exists.\n" +
  '> 2. `bun "$LLMWIKI_ROOT/src/cli.ts"` when `LLMWIKI_ROOT` is set — a host that copied this\n' +
  ">    skill folder OUT of the plugin (OpenClaw, Hermes, `skills add`) leaves step 1 pointing at\n" +
  ">    that host's skills directory, not at an engine.\n" +
  "> 3. `llmwiki` on PATH — the launcher `setup.sh` writes to `~/.local/bin`, or the npm bin.\n" +
  ">\n" +
  "> If none of the three resolve, say so once and stop. Do NOT guess a path: the engine writes\n" +
  "> into a repository, and a guessed root writes into the wrong one. Every `llmwiki …` or\n" +
  "> engine-CLI reference below means the invocation you resolved here.\n";

function skillBody(source: string, skillName: string): string {
  const generic = source
    .split(ENGINE_CLI_TOKEN)
    .join('bun "<plugin-root>/src/cli.ts"')
    .split("~/llmwiki")
    .join("<plugin-root>")
    .split("$HOME/llmwiki")
    .join("<plugin-root>");
  // SKILL.md frontmatter requires `name` alongside `description`; the sources carry only the
  // description (the installers name commands by filename). Inject it, then put the resolution
  // note right under the frontmatter so the rule precedes every engine reference.
  // …and the invocation gate alongside it (engine/skill-policy.ts documents why).
  const named = generic.startsWith("---\n")
    ? `---\nname: ${skillName}\n${FRONTMATTER_GATE}\n${generic.slice(4)}`
    : generic;
  const fmEnd = named.indexOf("\n---", 3);
  if (fmEnd < 0) return `${CODEX_CLI_NOTE}\n${named}`;
  const cut = fmEnd + "\n---\n".length;
  return `${named.slice(0, cut)}\n${CODEX_CLI_NOTE}${named.slice(cut)}`;
}

export function buildAssets(root: string = CLONE_ROOT): string[] {
  const written: string[] = [];
  for (const name of CLAUDE_COMMANDS) {
    const source = readFileSync(join(root, "skill", name), "utf-8");
    const skillName = name.replace(/\.md$/, "");
    const skillDir = join(root, "skills", skillName);
    mkdirSync(skillDir, { recursive: true });
    const sk = join(skillDir, "SKILL.md");
    writeFileSync(sk, `${skillBody(source, skillName).replace(/\n*$/, "\n")}\n${PLUGIN_MARK}\n`);
    written.push(sk);
    const policy = join(skillDir, SKILL_POLICY_REL);
    mkdirSync(dirname(policy), { recursive: true });
    writeFileSync(policy, skillPolicyYaml(source, skillName, PLUGIN_MARK.replace(/^<!-- | -->$/g, "")));
    written.push(policy);
  }
  return written;
}

if (import.meta.main) {
  for (const p of buildAssets()) console.log(`  ✓ ${p}`);
}
